name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [ Release ]
        runtime-identifier: [ 'win-x64', 'linux-x64' ]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Test with dotnet
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      run: dotnet test --configuration ${{ matrix.configuration }} --framework net6.0

    - name: Build with dotnet
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      run: dotnet publish --runtime ${{ matrix.runtime-identifier }} --configuration ${{ matrix.configuration }} --framework net6.0 --no-self-contained

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: TChapter-${{ matrix.runtime-identifier }}-net6.0
        path: TChapter/bin/${{ matrix.configuration }}/net6.0/${{ matrix.runtime-identifier }}/publish/
